import = [
    # "~/.config/alacritty/themes/themes/solarized_dark.toml"
]

[font]
size = 8.0

[font.normal]
family = "Noto Sans Mono Medium"
style = "Normal"

[shell]
args = ["-c", "cat ~/.config/wpg/sequences && zsh"]
program = "/bin/zsh"

[window]
opacity = 0.95
